media:
  - name: Baseball Photos
    path: images/baseball
  - name: Aviation Photos
    path: images/aviation
  - name: Misc Photos
    path: images/misc

content: [] # This hides that "Create new entry" text box you're seeing