content:
  - name: Baseball Photos
    type: collection
    path: images/baseball/
    exclude: ["index.html"] # Keeps things tidy
  - name: Aviation Photos
    type: collection
    path: images/aviation/
    exclude: ["index.html"]
  - name: Misc Photos
    type: collection
    path: images/misc/
    exclude: ["index.html"]